services:
  postgres:
    image: postgres:17
    container_name: ewallet-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ewallet
      POSTGRES_PASSWORD: ewallet_password
      POSTGRES_DB: ewallet_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: